const Provinsi = [
    { name: 'Aceh', code: 'AC' },
    { name: 'Bali', code: 'BA' },
    { name: 'Banten', code: 'BT' },
    { name: 'Bengkulu', code: 'BE' },
    { name: 'Yogyakarta', code: 'YO' },
    { name: 'Jakarta', code: 'JK' },
    { name: 'Jambi', code: 'JA' },
    { name: 'West Java', code: 'JB' },
    { name: 'Central Java', code: 'JT' },
    { name: 'East Java', code: 'JI' },
    { name: 'West Kalimantan', code: 'KB' },
    { name: 'Central Kalimantan', code: 'KT' },
    { name: 'South Kalimantan', code: 'KS' },
    { name: 'East Kalimantan', code: 'KI' },
    { name: 'North Kalimantan', code: 'KU' },
    { name: 'Riau Islands', code: 'KR' },
    { name: 'Lampung', code: 'LA' },
    { name: 'Maluku', code: 'MA' },
    { name: 'North Maluku', code: 'MU' },
    { name: 'West Nusa Tenggara', code: 'NB' },
    { name: 'East Nusa Tenggara', code: 'NT' },
    { name: 'Papua', code: 'PA' },
    { name: 'West Papua', code: 'PB' },
    { name: 'Riau', code: 'RI' },
    { name: 'South Sulawesi', code: 'SN' },
    { name: 'Southeast Sulawesi', code: 'SG' },
    { name: 'Central Sulawesi', code: 'ST' },
    { name: 'Gorontalo', code: 'GO' },
    { name: 'North Sulawesi', code: 'SA' },
    { name: 'West Sulawesi', code: 'SR' },
    { name: 'West Sumatra', code: 'SB' },
    { name: 'South Sumatra', code: 'SS' },
    { name: 'North Sumatra', code: 'SU' },
    { name: 'West Papua', code: 'PB' },
];

export { Provinsi };